name: two
favicon: null
layout_spectrum: 0.5733950288979884
typography_spectrum: 0.5691713285606601
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFF8E3'
    - '#CCCC9F'
    - '#33332D'
    - '#9FB4CC'
    - '#DB4105'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
